project_name: kubbernecker
dist: bin/
builds:
  - id: kubbernecker-metrics
    env:
      - CGO_ENABLED=0
    main: ./cmd/kubbernecker-metrics
    binary: kubbernecker-metrics
    goos:
      - linux
    goarch:
      - amd64
    ldflags:
      - -X github.com/zoetrope/kubbernecker.Version={{.Version}}
  - id: kubectl-kubbernecker
    env:
      - CGO_ENABLED=0
    main: ./cmd/kubectl-kubbernecker
    binary: kubectl-kubbernecker
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -X github.com/zoetrope/kubbernecker.Version={{.Version}}
    ignore:
      - goos: windows
        goarch: arm64
archives:
  - builds:
      - kubectl-kubbernecker
    name_template: "kubectl-{{ .ProjectName }}_{{ .Tag }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    wrap_in_directory: false
    format: tar.gz
    files:
      - LICENSE
    rlcp: true
dockers:
  - image_templates:
      - "ghcr.io/zoetrope/kubbernecker:{{ .Version }}"
    use: buildx
    dockerfile: ./Dockerfile
    ids:
      - kubbernecker-metrics
    extra_files:
      - LICENSE
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "dev"
changelog:
  use: github-native
