apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kubbernecker.fullname" . }}-config
  labels:
  {{- include "kubbernecker.labels" . | nindent 4 }}
data:
  kubbernecker-config.yaml: |
    namespaceSelector:
      matchLabels:
        role: {{ .Values.config.kubberneckerConfigYaml.namespaceSelector.matchLabels.role
          | quote }}
    targetResources: {{ toYaml .Values.config.kubberneckerConfigYaml.targetResources
      | nindent 6 }}