apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kubbernecker.fullname" . }}-config
  labels:
  {{- include "kubbernecker.labels" . | nindent 4 }}
data:
  kubbernecker-config.yaml: |
    namespaceSelector: {{ .Values.config.namespaceSelector | toYaml | nindent 6 }}
    targetResources: {{ .Values.config.targetResources | toYaml | nindent 6 }}
    enableClusterResource: {{ .Values.config.enableClusterResource }}
