apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubbernecker.fullname" . }}-metrics
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kubbernecker
    app.kubernetes.io/part-of: kubbernecker
  {{- include "kubbernecker.labels" . | nindent 4 }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kubbernecker.fullname" . }}-metrics
  labels:
    app.kubernetes.io/component: metrics
    app.kubernetes.io/created-by: kubbernecker
    app.kubernetes.io/part-of: kubbernecker
    control-plane: manager
  {{- include "kubbernecker.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      control-plane: manager
    {{- include "kubbernecker.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        control-plane: manager
      {{- include "kubbernecker.selectorLabels" . | nindent 8 }}
      annotations:
        kubectl.kubernetes.io/default-container: manager
    spec:
      containers:
      - args:
        - --config-file=/etc/kubbernecker/kubbernecker-config.yaml
        command:
        - /kubbernecker-metrics
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ .Values.kubernetesClusterDomain }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        name: manager
        ports:
          - name: health
            containerPort: 8081
            protocol: TCP
          - name: metrics
            containerPort: 8080
            protocol: TCP
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources: {{- toYaml .Values.resources | nindent 10 }}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        volumeMounts:
        - mountPath: /etc/kubbernecker
          name: config
      securityContext:
        runAsNonRoot: true
      serviceAccountName: {{ include "kubbernecker.fullname" . }}-metrics
      terminationGracePeriodSeconds: 10
      volumes:
      - configMap:
          name: {{ include "kubbernecker.fullname" . }}-config
        name: config
