apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: clusterrolebinding
    app.kubernetes.io/instance: metrics-rolebinding
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kubbernecker
    app.kubernetes.io/part-of: kubbernecker
    app.kubernetes.io/managed-by: kustomize
  name: metrics-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: metrics-role
subjects:
- kind: ServiceAccount
  name: metrics
  namespace: system
