apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: serviceaccount
    app.kubernetes.io/instance: metrics-sa
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kubbernecker
    app.kubernetes.io/part-of: kubbernecker
    app.kubernetes.io/managed-by: kustomize
  name: metrics
  namespace: system
