apiVersion: apps/v1
kind: Deployment
metadata:
  name: metrics
  namespace: system
spec:
  template:
    spec:
      securityContext: null
      containers:
        - command:
            - /kubbernecker-metrics
          args: null
          name: manager
          securityContext: null
          resources: null
