apiVersion: apps/v1
kind: Deployment
metadata:
  name: manager
  namespace: system
spec:
  template:
    spec:
      securityContext: null
      containers:
        - command:
            - /kubbernecker
          args: null
          name: manager
          securityContext: null
          resources: null
