name: CI
on:
  pull_request:
  push:
    branches:
    - 'main'
jobs:
  test:
    name: Test
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version-file: go.mod
        cache: true
    - uses: aquaproj/aqua-installer@v2.0.2
      with:
        aqua_version: v1.32.3
    - run: make test
